$reportDir = Join-Path $PSScriptRoot "..\reports"
$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$architecture = Get-Content "$reportDir\architecture.txt" -Raw
$circular = Get-Content "$reportDir\circular.txt" -Raw
$deadcode = Get-Content "$reportDir\deadcode.txt" -Raw

$lines = @()

$lines += "# Gr8Books Neo QA Report"
$lines += ""
$lines += "**Generated:** $date"
$lines += ""
$lines += "---"
$lines += ""
$lines += "## Architecture"
$lines += ""
$lines += $architecture
$lines += ""
$lines += "---"
$lines += ""
$lines += "## Circular Dependencies"
$lines += ""
$lines += $circular
$lines += ""
$lines += "---"
$lines += ""
$lines += "## Dead Code"
$lines += ""
$lines += $deadcode
$lines += ""
$lines += "---"
$lines += ""
$lines += "_Generated by Gr8Books Neo Automation Toolkit_"

$lines | Set-Content "$reportDir\QA-Report.md"

Write-Host ""
Write-Host "====================================="
Write-Host " QA Report Generated Successfully"
Write-Host "====================================="
Write-Host ""
Write-Host "reports\QA-Report.md"