param(
    [Parameter(Mandatory = $true)]
    [string]$ReportDir
)

$ErrorActionPreference = "Continue"

New-Item -ItemType Directory -Force $ReportDir | Out-Null

function Read-Report {
    param(
        [string]$Path,
        [string]$Fallback
    )

    if (Test-Path $Path) {
        $content = Get-Content $Path -Raw
        if (-not [string]::IsNullOrWhiteSpace($content)) {
            return $content.Trim()
        }
    }

    return $Fallback
}

$architecture = Read-Report `
    (Join-Path $ReportDir "architecture.txt") `
    "No architecture findings were produced."

$circular = Read-Report `
    (Join-Path $ReportDir "circular.txt") `
    "No circular dependency findings were produced."

$deadcode = Read-Report `
    (Join-Path $ReportDir "deadcode.txt") `
    "No dead code findings were produced."

# ------------------------------------------------------------
# Determine Status
# ------------------------------------------------------------

if ($architecture -match "(?i)no dependency violations found") {
    $architectureStatus = "Passed"
}
elseif ($architecture -match "(?i)(violation|error|failed|could not resolve)") {
    $architectureStatus = "Needs Review"
}
else {
    $architectureStatus = "Review Required"
}

if ($circular -match "(?i)no circular dependency found") {
    $circularStatus = "Passed"
}
elseif ($circular -match "(?i)(found.*circular|cycle detected)") {
    $circularStatus = "Needs Review"
}
else {
    $circularStatus = "Review Required"
}

if ($deadcode -match "(?i)(unused|not used|dead code)") {
    $deadcodeStatus = "Needs Review"
}
else {
    $deadcodeStatus = "Passed"
}

if (
    $architectureStatus -eq "Passed" -and
    $circularStatus -eq "Passed" -and
    $deadcodeStatus -eq "Passed"
) {
    $overallStatus = "READY TO MERGE"
}
else {
    $overallStatus = "DEVELOPER REVIEW REQUIRED"
}

$generated = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$report = @"
# Gr8Books Neo Backend Advisory Report

Generated:
$generated

------------------------------------------------------------

OVERALL STATUS

$overallStatus

------------------------------------------------------------

| Analysis | Status |
|----------|--------|
| Architecture | $architectureStatus |
| Circular Dependencies | $circularStatus |
| Dead Code | $deadcodeStatus |

------------------------------------------------------------

ARCHITECTURE ANALYSIS

$architecture

------------------------------------------------------------

CIRCULAR DEPENDENCY ANALYSIS

$circular

------------------------------------------------------------

DEAD CODE ANALYSIS

$deadcode

------------------------------------------------------------

Developer Action

If any section is marked "Needs Review":

1. Fix the issue.
2. Commit the fix.
3. Push again.
4. Re-run the QA workflow.

If the finding is a false positive:

- Explain why.
- Reference the file.
- Continue with the PR.

------------------------------------------------------------

Generated by Gr8Books Neo Automation Toolkit
"@

$report | Set-Content `
    (Join-Path $ReportDir "QA-Report.md") `
    -Encoding UTF8

Write-Host ""
Write-Host "========================================"
Write-Host "QA Report Generated Successfully"
Write-Host "========================================"
Write-Host "Status : $overallStatus"
Write-Host "Output : $(Join-Path $ReportDir 'QA-Report.md')"
Write-Host ""